//APP
export const APP_INITIALIZED = 'APP_INITIALIZED'

// PROFILE
export const PROFILE_POST_ADD = 'PROFILE_POST_ADD';
export const PROFILE_DELETE_POST = "PROFILE_DELETE_POST"
export const PROFILE_SET_USER_PROFILE = "PROFILE_SET_USER_PROFILE"
export const PROFILE_SET_STATUS = "PROFILE_SET_STATUS"
export const UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT';

// USERS
export const USERS_FOLLOW = "USERS_FOLLOW"
export const USERS_UNFOLLOW = "USERS_UNFOLLOW"
export const USERS_SET = "USERS_SET"
export const USERS_SET_CURRENT_PAGE = "USERS_SET_CURRENT_PAGE"
export const USERS_SET_TOTAL_COUNT = "USERS_SET_TOTAL_COUNT"

export const USERS_IS_LOADING = "USERS_IS_LOADING"
export const USERS_FOLLOWING_IN_PROGRESS = "USERS_FOLLOWING_IN_PROGRESS"



//DIALOGS
export const DIALOGS_UPDATE_NEW_MESSAGE_BODY = "DIALOGS_UPDATE_NEW_MESSAGE_BODY";
export const DIALOGS_SEND_MESSAGE = "DIALOGS_SEND_MESSAGE";

// AUTH
export const AUTH_SET_USER_DATA = "AUTH_SET_USER_DATA"





